### ISSUE TITLE
Validation Rate

### ISSUE THREAD

**Issue by CaesarOG** [agencyrevolution/EmailValidator#1]
Hi, I'm using this package as a microservice on an AWS ec2 instance. There is a bash script (validator) that runs through a csv of emails, and calls a node script (requestEmails) with the individual emails as arguments. 

[validator.txt](https://github.com/agencyrevolution/EmailValidator/files/556474/validator.txt)
[requestEmails.txt](https://github.com/agencyrevolution/EmailValidator/files/556475/requestEmails.txt)
[emailValServer.txt](https://github.com/agencyrevolution/EmailValidator/files/556481/emailValServer.txt)

My code is simple, requestEmails is called for each email by validator.sh  and requestEmails makes a call to your microservice and saves it to another csv if the email is returned as valid. The emailValServer  is where is set up the microservice. 

It gets through 10k emails a day but claims only 10% are valid while services like emaillistverify.com
outputs about 55% for the same list of emails. A lot of the responses for the invalid emails just say "reason":"false"   as the explanation for why it's invalid, which is curious. Most of the emails with this reason for invalid are claimed as valid by emaillistverify.com . I don't think there is any issue with Redis config because there ARE valid emails being accumulated, but 10% doesn't make sense when others say 55%. Any thoughts on why this might be occuring? Thanks for taking the time to read this.

**Comment by lucasjans** [comment]
You're going to have to debug, look into the logs and report back. Keep in mind if you hit the same IP address too much you're going to get false positives.
